question_data = [
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "text": "French is an official language in Canada.", "answer": "True",
 ("in%ss" % "answer"): ["False"]},
{"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
 "text": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
 "answer": "False", ("in%ss" % "answer"): ["True"]},
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "text": "Nutella is produced by the German company Ferrero.",
 "answer": "False", ("in%ss" % "answer"): ["True"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "text": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
 "answer": "True", ("in%ss" % "answer"): ["False"]},
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "text": "Bulls are attracted to the color red.", "answer": "False",
 ("in%ss" % "answer"): ["True"]},
{"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
 "text": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
 "answer": "True", ("in%ss" % "answer"): ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "text": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
 "answer": "False", ("in%ss" % "answer"): ["True"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "text": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
 "answer": "True", ("in%ss" % "answer"): ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "text": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
 "answer": "False", ("in%ss" % "answer"): ["True"]}]
